a =input('enter 1st number:')
b =input('enter  2nd number:')
print(a)
print(type(a))
print(b)
print(type(b))
print(a+b)
print(type(a+b))
print('---------------------------')
s =int(a)
print(s)
print(type(s))
n =int(b)
print(n)
print(type(s))
print(s+n)
print(type(s+n))
