y =input('enter 1st no:')
z =input('enter 2nd no:')
print(y)
print(type(y))
print(z)
print(type(z))
print(y+z)
print(type(y+z))
print('---------------------------------')              #   converting the str to complex
w =complex(y)
print(w)
print(type(w))
x =complex(z)
print(x)
print(type(x))
print(w+x)
print(type(w+x))