s =input('enter 1st no:')
z =input('enter 2nd no:')
print(s)
print(type(s))
print(z)
print(type(z))
print(s+z)
print('------------------------------------') # converting str to bool
x =bool(s)
print(x)
print(type(x))
y =bool(z)
print(y)
print(type(y))
print(x+y)
print(type(x+y))
