x =input('enter a 1st no:')
y =input('enter a 2nd no:')
print(x)
print(type(x))
print(y)
print(type(y))
print(x+y)
print('---------------------------------------') # converting str to float
a =float(x)
print(a)
print(type(a))
b =float(y)
print(b)
print(type(b))
print(a+b)
print(type(a+b))